### ISSUE TITLE
Error: Undefined variable: "$aqua"

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ui#10]
**Describe the bug**
Installation and setup lands me with this in the console:
```
Error: Undefined variable: "$aqua".
```

**To Reproduce**
1. Follow instructions
2. Run the consumer app.

**Expected behavior**

**Comment by allthesignals** [comment]
Importing the settings does not fix the issue.

**Comment by allthesignals** [comment]
@andycochran Yeah, I deleted it and had the same issue.

**Comment by andycochran** [comment]
Closing this, as I cannot reproduce. I assume that `labs-ui/variables` was not imported properly in the consuming app, as `$aqua` is its first defined var.
