### ISSUE TITLE
numberMenuItems

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-ui#14]
The `numberMenuItems` computed property isn't working right in the Accordion Menu component. It should compute a count of children with active states and show that number in the handlebars.

**Comment by andycochran** [comment]
@allthesignals, we might need you for this one.

**Comment by andycochran** [comment]
This is currently a blocker in [ZoLa](https://github.com/NYCPlanning/labs-zola), where we lost this a while back. However, now it's needed for the new print view feature. 

As-is, we can’t know if a layer group container has any active layer groups, and can’t hide the title from the print legend. See the empty sections: 

<img src="https://user-images.githubusercontent.com/409279/52291284-0761b380-2940-11e9-9182-50c837d41c0b.png" width=300 />

**Comment by allthesignals** [comment]
Do you need me to work on this? We could use a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) for this. Layer-group components would be yielded from their parent containers, and upon invocation, could register children onto the parent group Map via init.
