### ISSUE TITLE
Security Warnings

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ui#29]
We should make sure to sanitize these - they are the cause of the very long `console.trace` issues.

> Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes. Style affected: "color:rgba(0, 122, 0, 1);"

> Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see https://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes. Style affected: "color:rgba(179, 255, 179, 1);"

**Comment by andycochran** [comment]
Is this still happening? How can I replicate these errors?

**Comment by allthesignals** [comment]
Not sure - I think they were happening in tooltip. Anywhere the style attribute is computed...

**Comment by andycochran** [comment]
Maybe is was Tooltipster? I'm not seeing it now.

**Comment by andycochran** [comment]
I'm going to close this for now (assuming ditching Tooltipster for Ember Tooltips resolved it). We can reopen w/ instructions to reproduce if we see notice it again.
