### ISSUE TITLE
site-header should yield multiple blocks

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-ui#42]
**Is your feature request related to a problem? Please describe.**
Site-header doesn't allow for a ton of flexibility with the markup. 

**Describe the solution you'd like**
We should use this [solution](https://dockyard.com/blog/2018/11/26/how-to-yield-an-ember-component-in-multiple-places) for yielding multiple markup blocks.

**Comment by allthesignals** [comment]
Cool! I didn't even notice. How does the nav one work? 

I opened this because I ran across this blog post then recall seeing this issue with site-header at some point earlier last year. We can close

**Comment by andycochran** [comment]
It works like [this](https://ui.planninglabs.nyc/?anchor=site-header). ☺️


(It's just a place to put a menu, which adjusts the layout for mobile. There's no specific navigation functionality; that's for the consuming app to do.)

**Comment by allthesignals** [comment]
@andycochran oh AWESOME - this implements that blog post exactly. When you yield multiple hashes, those hashes seem to get merged together. Awesome. Do you know if it was that blog post that inspired this or did you just discover it on your own? This is a really simple way to solve the multiple "block slots" problem. Would love a blog post about this promote addons for team UI patterns/lookbooks.
